export const editButton = document.querySelector(".profile__edit-btn"); // выбираем кнопкну редактировать в профиле
export const popUp = document.querySelector(".popup"); // выбираем блок попап для редактирования профиля
export const popupClose = document.querySelector(".popup__close-btn"); // кнопка закрытия формы редактирования профиля
export const nameInput = document.querySelector(".popup__field_name"); // форма ввода имени в попапе редактирования профиля
export const jobInput = document.querySelector(".popup__field_about"); // форма ввода о себе в попапе редактирования профиля
export const name = document.querySelector(".profile__name"); // выбор имени в профиле
export const job = document.querySelector(".profile__about"); // Выбор профессии в профиле
export const formElement = document.querySelector(".popup__content"); // находим форму редактирования профиля в DOM
export const elements = document.querySelector(".elements"); // находим в DOM блок element
export const addButton = document.querySelector(".profile__add-btn"); // кнопка добавления карточки в DOM
export const popupAddCard = document.querySelector(".popup_card"); // блок попап добавления карточки в DOM
export const cardPopupCloseBtn = document.querySelector("#cardPopupCloseBtn"); // кнопка закрытия попапа добавления карточкив DOM
export const cardName = document.querySelector("#cardName"); // поле имени картинки попапа добавление карточки в DOM
export const cardUrl = document.querySelector("#cardUrl"); // поле добавления ссылки на картинкинку ПДК в DOM
export const formCardElement = document.querySelector("#formCardElement"); // ПДК в DOM
export const popupImage = document.querySelector(".popup_image"); // попап с картинкой
export const popupImageCloseBtn = document.querySelector("#popupImageCloseBtn"); // закрытие попапа с картинкой
export const popups = Array.from(document.querySelectorAll(".popup")); // массив всех попапов для закрытия по еск
export const forms = Array.from(document.querySelectorAll('.popup__content')); // массив форм